@startuml robot_car

[*] --> Finding_target : signal not found
Finding_target --> Finding_target : signal not found
Finding_target : Servo motor rotates with photodiode
Finding_target : Photoediode seeks photoemitter signal
Finding_target --> Navigation : target located


state Navigation{
    Reorientation : Read servo motor angle
    Reorientation : Calculate angular velocity
    Reorientation : Move motors until MPU == angular velocity
    Reorientation --> Move : MPU == angular velocity

    Move : Move forward 
    Move : Check for obstacle (ultrasonic sensor)
    Move --> Move : No obstacle

    Move --> Obstacle_avoidance : Obstacle detected
    Obstacle_avoidance : Stop distance x from obstacle
    Obstacle_avoidance : Navigate round obstacle
    Obstacle_avoidance --> Move : Obstacle not detected

}

Navigation --> Destination_arrival : signal not found
Destination_arrival : Stop

Destination_arrival --> [*]

@enduml